### ISSUE TITLE
Manage python cross-plugins dependencies

### ISSUE THREAD

**Issue by elpaso** [qgis/QGIS-Enhancement-Proposals#132]
# QGIS Enhancement: Manage python cross-plugins dependencies

**Date** 2018/11/18

**Author** Alessandro Pasotti (@elpaso)

**Contact** elpaso at itopen dot it

**maintainer** @elpaso 

**Version** QGIS 3.6

# Summary

The use case is for plugin authors that want to install other plugins during the installation of their plugins.

## Proposed Solution

A new optional metadata entry will be added to `metadata.txt`: `plugin_dependencies`

The metadata will contain a comma separated list of plugin names, with a format similar of the one used by `pip`, with optional version.

After a successful plugin installation, if the plugin has any unsatisfied dependency, a dialog will pop-up (title is provisional):

![immagine](https://user-images.githubusercontent.com/142164/48254007-084e7c00-e409-11e8-908c-6a2cc69cf81c.png)

### Example(s)

`plugin_dependencies = QuickMapServices==0.19.10.1,QuickWKT`

### Affected Files

Python only: plugin manager

## Performance Implications

None

## Backwards Compatibility

No issues

## Votes

(required)

**Comment by luipir** [comment]
+1, any api to satisfy dependencies programmatically instead to do it manually via pluginManager, something like:
status = pluginManager.dependencyManager(<targetPlugin>)
status.setParameter({dep1:Upgdade, dep2:downgrade, etc etc}
errors = status.resolveDependency()

**Comment by nyalldawson** [comment]
I'm curious as to the implications this has on plugin api. (Given that most plugins wouldn't have a stable api). Is it effectively a "use at own risk" thing, where plugin authors just have to be aware that relying on someone else's plugin isn't stable?

**Comment by elpaso** [comment]
@rduivenvoorde we could have both: the buttons (install, upgrade etc.) and the checkboxes for mass action, I didn't see yet a use case for massive dependencies but who knows?

**Comment by nyalldawson** [comment]
@elpaso 

I've been thinking about this one lately. 

One issue we have with processing is that it's not well defined which parts of the Python processing code are stable API, and which are just internal classes/methods exposed because Python exposes everything.

This leads to a tricky situation where some `from processing.... import ...` statements are correct and import only stable API, others are fragile and relying on API which will change.

@NathanW2 recently added the decorator support for Processing by adding his new API to the `qgis.processing` module -- so users have to go `from qgis.processing import ...`. I very much like this separation, and think we should do this more. So anything from `qgis.*` is stable API, anything outside (like `from processing.whatever`) is NOT STABLE and importing is at users own risk.

Perhaps this could be considered here. Plugins which want to expose some form to "public" stable api could inject them into a `qgis.3rdparty` or `qgis.plugins` module, and in doing so make a public declaration that they won't remove or break that API. E.g.

    from qgis.plugins.QuickWkt import quick_wkt_parser

is stable API, but

    from QuickWkt.gui.dialogs.SomeDialog import SomeDialog

is not, and other plugins which do this are doing so at their own risk.

**Comment by mbernasocchi** [comment]
@elpaso should this be closed?

**Comment by elpaso** [comment]
> @elpaso should this be closed? since it is implemented in #9619

yes
