### ISSUE TITLE
QgsRasterProjector optimization with linear interpolation

### ISSUE THREAD

**Issue by dmarteau** [qgis/QGIS-Enhancement-Proposals#214]
# QGIS Enhancement: QgsRasterProjector optimization with linear interpolation

**Date** 2021/03/18

**Author** David Marteau (@dmarteau)

**Contact** dmarteau at 3liz dot com

**maintainer** @dmarteau

**Version** QGIS 3.20

# Summary

The raster reprojection is very slow compared to other products (compared to [`MapServer`](https://github.com/MapServer/MapServer) for example). Using HotSpot profiling showed that on a lightweight Geotiff reading/reprojection about 49% of time is spent in  [`QgsRasterProjector::block`](https://github.com/qgis/QGIS/blob/master/src/core/raster/qgsrasterprojector.cpp#L776) and 25% is spent in the calculation of the inverse pixel transfom [`ProjectorData::srcRowCol`](https://github.com/qgis/QGIS/blob/master/src/core/raster/qgsrasterprojector.cpp#L469) method.

Even Rouault pointed that the [MapServer](https://github.com/MapServer/MapServer) and the Gdal reprojection implementation used an acceleration method based on a piecewise linear approximation of the pixel transformation when some precision requirements where meet.

## Discussion Réferences

* http://osgeo-org.1560.x6.nabble.com/QGIS-Developer-The-virtual-QgsRasterInterface-block-method-is-too-slow-td5446987.html

## Proposed Solution

The proposed solution is to use the same method as used in [`MapServer`](https://github.com/MapServer/MapServer/blob/main/mapresample.c#L948): i.e  replace the call to [`srcRowCol`](https://github.com/qgis/QGIS/blob/master/src/core/raster/qgsrasterprojector.cpp#L850) by the linar approximation of the pixels along the scanline using start, end and middle point of the scanline.

The applicability of the approximation is based on a error value comparison - which could be parametrized from settings. The test is done once by scanline (no recursivity), if applicable, each pixel in the scanline is interpolated instead of calling `srcRowCol`.

### Réferences

* [Mapserver interpolation implementation](https://github.com/MapServer/MapServer/blob/main/mapresample.c#L948)
* [Gdal interpolation implementation](https://github.com/OSGeo/gdal/blob/master/gdal/alg/gdaltransformer.cpp#L3337)

### Quote from the Gdal implementation

```
This function creates a context for an approximated transformer.  Basically
a high precision transformer is supplied as input and internally linear
approximations are computed to generate results to within a defined
precision.

The approximation is actually done at the point where GDALApproxTransform()
calls are made, and depend on the assumption that the roughly linear.  The
first and last point passed in must be the extreme values and the
intermediate values should describe a curve between the end points.  The
approximator transforms and center using the approximate transformer, and
then compares the true middle transformed value to a linear approximation
based on the end points.  If the error is within the supplied threshold
then the end points are used to linearly approximate all the values
otherwise the inputs points are split into two smaller sets, and the
function recursively called till a sufficiently small set of points if found
that the linear approximation is OK, or that all the points are exactly
computed.

This function is very suitable for approximating transformation results
from output pixel/line space to input coordinates for warpers that operate
on one input scanline at a time.  Care should be taken using it in other
circumstances as little internal validation is done, in order to keep things
fast.
```

### Affected Files

* https://github.com/qgis/QGIS/blob/master/src/core/raster/qgsrasterprojector.cpp

## Performance Implications

As a rule of thumb, should increase raster reprojection around 20% performance gain (according to HotSpot results)

## Backwards Compatibility

No incompatibility

**Comment by nyalldawson** [comment]
I must admit that I don't fully comprehend the maths inside QgsRasterProjector, but my understanding of the code is that it iteratively builds a grid of approximate transforms and bails out as soon as an appropriate approximation threshold is reached. That already sounds similar to the proposed approach here, so I'm wondering how confident you are that the reworked approach will actually lead to speed improvements?

**Comment by dmarteau** [comment]
> I must admit that I don't fully comprehend the maths inside QgsRasterProjector

Me neither, but as it seems  that `QgsRasterProjector` is never called with the `QgsRasterProjector::Approximate` flag: references to this flags is found only in https://github.com/qgis/QGIS/blob/master/src/providers/grass/qgsgrassoptions.cpp#L74.

Because the default is to compute a "non approximated" sampling it really seems that the "approximate" method is never used:  then the sampling resume to  a call to [`ProjectorData::preciseSrcRowCol`](https://github.com/qgis/QGIS/blob/master/src/core/raster/qgsrasterprojector.cpp#L469) which is quite straightforward to follow - and resume itself to a call to [`QgsCoordinateTransform::transformInPlace`]() call.

> so I'm wondering how confident you are that the reworked approach will actually lead to speed improvements?

The method proposed here is far simpler - but nevertheless efficient according to MapServer and Gdal implemention - and far easier to understand that  the - not - used approximate method of `ProjectorData`. So I'm quite confident that there will be some improvement;  in any case this will have to be tested carefully.

**Comment by rouault** [comment]
I'm just discovering the "approximate" method of QgsRasterProjector. From my understanding, in approximate and exact code paths  a target coordinates to source coordinates array is computed in an iterative way starting for 3x3, and adding rows and columns when needed until the error between a linear approximation and exact coordinate reprojection is less than the target resolution, ie one target pixel (which is quite coarse. gdalwarp default is 1/8 th of a target pixel). This matrix is used in both cases to determine the source extent to query. In the approximate mode, it is also used to perform the raster reprojection, whereas in the exact mode, all points are transformed.
One defect of the current approximate mode is that it creates a matrix as the structure of interpolation which implies that non-linearities are constant over the whole area of interest (which is probably fair enough is zooming in sufficiently, but not on zoom on all Earth situations), which can (I think) lead to a bigger matrix than the GDAL/mapserver piecewise per-row method needs. And I also think that in its iterations it does more reprojections than the GDAL/mapserver method does.

Regarding the computation of the source extent, it would be interesting to look a the time the current method takes. I suspect it might larger than what is really needed. I'm wondering if the one-target pixel error threshold that is used to compute iteratively the matrix isn't much larger than we need. GDAL has a GDALWarpOperation::ComputeSourceWindow() method ( https://github.com/OSGeo/gdal/blob/e984e8fba5b45396cfe0e8872911a2d894ca7429/gdal/alg/gdalwarpoperation.cpp#L2545 ) that serves that purpose. It isn't entirely bullet proof in its default mode when reprojecting from polar since it uses just sampling along the edges of the target window, but when using the 20x20 grid step approach, and adding a few source pixels as a margin, this is generally good enough. My instinct is that QGIS method is probably more bullet-proof, but at the expense of a likely overwhelming computation time (an easy experiment would be to keep it and see the effect of relaxing the error threshold)

That said the 1/8 th target pixel approximation used by GDAL / Mapserver is mostly useful only if applying an interpolation of the raster values (bilinear, bicubic). For the nearest-neighbour approach of QGIS, it is likely of little value.
An interesting experiment would be to see if enabling by default the Approximate current implementation leads to significant performant improvement and the effect on the output quality.

**Comment by dmarteau** [comment]
Thank you very much @rouault  for your clarification !  

 +10 for enabling the current method for testing.

**Comment by nyalldawson** [comment]
Thanks for the insights @rouault !

Can I make one additional request here: a very similar optimisation would HUGELY benefit vector layer rendering too. Currently we do precise transformations of every vertex in a dataset, which can be complete overkill for visualisation at smaller scales, and contributes substantially to the render time of vector layers. An interpolated approach would also be very useful for vector rendering (and a MASSIVE benefit to point clouds too!)

If you're reworking the raster projector class, I'd request that you do this in a way that separates out the "interpolated projector" logic from the raster specific logic so that we can reuse the common "interpolated projector" class elsewhere (ie when rendering vectors, point clouds, meshes, ...). Then we go from just improving raster render time to improving ALL qgis render time :partying_face: 

In fact, we could even potentially share precalculated interpolated projectors between different layers (with the same source CRS) at render time, so e.g if the user had multiple vectors, a point cloud, and a mesh in one common source CRS we could determine that the interpolator has already been calculated for another layer and just take that for reuse with all the other layers without having to calculate it for all of them individually...

**Comment by rouault** [comment]
> separates out the "interpolated projector" logic from the raster specific logic so that we can reuse the common "interpolated projector" class elsewhere

Having a generic solution isn't completely obvious to me. The raster interpolation method uses by GDAL/MapServer is simple in the fact that it assumes that if a target pixel P located on a segment [A, B], and that segment is small enough, then the source pixel CT(P) is located at the same ratio on the source segment [CT(A), CT(B)], and if refinement is needed, the intermediate you compute exactly are directly useful for the final computation.
For vector geometries, it is very unfrequent that you have N points consecutively aligned on a linestring. So you'd have to use other interpolation technics, like a barycentric/triangular one (https://en.wikipedia.org/wiki/Barycentric_coordinate_system). Finding which points to select might be tricky. Or maybe use an interpolation grid like done in the current QGIS approximate raster reprojector, and perform bilinear interpolation from that.

**Comment by nyalldawson** [comment]
> Or maybe use an interpolation grid like done in the current QGIS approximate raster reprojector, and perform bilinear interpolation from that.

That's what I had in mind

**Comment by nyalldawson** [comment]
Not sure if you still monitor these repositories, but if @blazek is listening you may have valuable feedback here too (as the original author of this work)?

**Comment by dmarteau** [comment]
Wouldn't it be better to proceed one step at a time ?

1. Enable the actual method for  QgsRasterProjector, 
2. Evaluate performance gain
3. If this  is satisfactory, then generalize to vector layer rendering.

**Comment by blazek** [comment]
When I implemented raster reprojection (QGIS hackfest Wroclaw 2010), it appeared that precise reprojection is too slow and mostly useless for data viewing. I had to write approximated reprojection which was stolen from another program or some artical. It is strange that there is no reference to the original code. I am used to steal peaces of code but always with reference.

It sounds strange that approximated reprojection is disabled and even stranger if nobody noticed when it was disabled. The difference should be huge, say 10 times slower. I cannot believe it is not used.

**Comment by nyalldawson** [comment]
@blazek 

I think @dmarteau has misinterpreted the code -- the projector IS approximate by default. See https://github.com/qgis/QGIS/blob/master/src/core/raster/qgsrasterprojector.h#L123

**Comment by dmarteau** [comment]
Ooops, my bad, didn't catch the  initializer...

**Comment by blazek** [comment]
The ideas behind the code come probably from https://docs.oracle.com/cd/E17802_01/products/products/java-media/jai/forDevelopers/jai-apidocs/javax/media/jai/WarpGrid.html

**Comment by blazek** [comment]
In the summary and in the original ML thread there is mentioned "49% of time is spent in QgsRasterProjector::block and 25% is spent in the calculation of the inverse pixel transform ProjectorData::srcRowCol method". What I am missing is a clear comparison between QGIS and GDAL.

**Comment by dmarteau** [comment]
> What I am missing is a clear comparison between QGIS and GDAL.

The primary assumption was that optimisation was not activated in Qgis. The original comparison was not between GDAL and QGIS, but between QGIS and MapServer.

**Comment by rldhont** [comment]
@blazek The original comparison was between a QGIS Server and a MapServer WMS GetMap request with only 1 GeoTIFF layer. The difference is 1000ms for QGIS Server and 200ms for MapServer. For this request  QGIS Server spent 49% of this time in QgsRasterProjector::block.

**Comment by blazek** [comment]
The mSqrTolerance value and how errors are checked should be reconsidered. Currently the error is checked between destination point on CP matrix and precise destination point transformed from source point approximated from source points on both sides of source point corresponding to destination point. In other words, half density CP matrix is being checked and real error when full density matrix is used is lower.

Using half or even lower mSqrTolerance could be sufficient, but there must be done some reasoning.  The error checking could be probably optimized. 

It would be interesting to have profiling for methods in QgsRasterProjector and ProjectorData to see how long takes to create CP matrix and how much time is spent  in checkRows/Cols for example. 25% in srcRowCol() also seems to much.

Another question is how many bands had the raster. ProjectorData with CP matrix is created in every QgsRasterProjector::block, it could be interesting to implement some sort of CP matrix cache, what nyalldawson already noticed.

We don't even know if approximation was really used in the benchmark, because CP matrix calculation stops if CP size is > 0.25 destination size. Long time spent in srcRowCol() could suggest that it is calling preciseSrcRowCol().

If you are lazy, you can try to use mSqrTolerance /= 2 and do benchmark with a single band raster as a starting point.

**Comment by blazek** [comment]
Correction: mSqrTolerance *= 4

**Comment by rldhont** [comment]
Hi @blazek, I have tested `mSqrTolerance *= 4` and nothing has changed.

In my case, the raster is a GeoTIFF with these specifications:
* CRS: +proj=aea +lat_1=43 +lat_2=62 +lat_0=30 +lon_0=-30 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0
* Extent: -6687479.3793354798108339,-1256807.7098174802958965 : 5587520.6206645201891661,5568192.2901825197041035
* Unit: meters
* Width: 491
* Height: 273
* Pixel Size: 25000,-25000

And the WMS GetMap request has these parameters:
* CRS: EPSG:3857
* Extent: -6257593.143380252,4373571.996305524 : 3698543.814443155,8039712.01150404
* Unit: meters
* Width: 2036
* Height: 750

The `approximateSrcRowCol` is used and the request takes 1000ms with 25% in `srcRowCol()` in MapServer the same WMS GetMap Request takes 200ms.

**Comment by blazek** [comment]
Thank you for test. I have no more simple solutions.

How does look the comparison without reprojection, rendered in WGS84? 

Is it single band?

If it is in approximateSrcRowCol(), it should be possible to optimize it, it must be fast, it is just looking for source cell in CP matrix.

**Comment by rldhont** [comment]
Hi @blazek, I made test with a single band GeoTIFF.

I made these tests : 
* disable approximate rendered in EPSG:3857
* force approximate rendered in EPSG:3857
* rendered in WGS84

In these 3 tests, the requests take approximately between 900ms to 1000ms.
* the faster seems to be the requests rendered in WGS84
* the slower seems to be the requests with force approximate rendered in EPSG:3857

**Comment by blazek** [comment]
@rldhont thank you and sorry, I overlooked that your source tif is in AEA. Could you please also try to render it in the original AEA to see how long it takes without reprojection?

> the slower seems to be the requests with force approximate rendered in EPSG:3857

It is expected to be slower with 'difficult' projections where it starts to calculate CP matrix but it does not reach desired error threshold with CP count lest than 25% of target cells count. Then it falls back to exact projection of each cell. This can happen with polar projections and AEA could be a candidate. That is not however the case with your tests if approximateSrcRowCol() is called. 

We should look deeper into approximateSrcRowCol() profiling.

> force approximate rendered in EPSG:3857

If approximate is 'forced' with a difficult projection, it may result in calculation of CP matrix with the same size as target raster and then of course it is slower. But that does no seem to be our case.

It would be interesting to know, if it is so bad also with 'easy' (similar) projections.

**Comment by nyalldawson** [comment]
Hey @blazek -- just wanted to acknowledge your efforts and helpfulness in this thread, and sincerely thank you for all the valuable insights you've provided! 👍

**Comment by mbernasocchi** [comment]
> This QEP is probably not relevant anymore.

@dmarteau does this mean you retire the grant application?

**Comment by anitagraser** [comment]
@dmarteau We'll be starting the voting process tomorrow evening. Please let us know if you want to proceed with this application by April 8th 17:00 CET latest. Otherwise, we'll assume that this QEP is not relevant anymore.

**Comment by dmarteau** [comment]
This QEP is not relevant anymore (It needs more tests and inputs ), the grant application should be retired but I cannot do it my self since I have not the required permission.

**Comment by anitagraser** [comment]
@rldhont could you please close this issue? Thank you!
