### ISSUE TITLE
Implicit PR acceptance after 2 weeks with no review

### ISSUE THREAD

**Issue by nyalldawson** [qgis/QGIS-Enhancement-Proposals#303]
# QGIS Enhancement: Implicit PR acceptance after 2 weeks with no review

**Date** 2024/10/24

**Author** Nyall Dawson

**Contact** nyall dot dawson at gmail dot com

# Summary

Currently, pull requests must be be reviewed by a QGIS developer with commit rights prior to the main repo prior to being merged into master. While this is an ideal approach for code stability, unfortunately the QGIS development community has a workload issue and it is **extremely** difficult to get a pull request reviewed. This can take many weeks, months or even years.

In this QEP I propose a change to policy to permit pull request merging by core developers after a two week period with no comments.

_This QEP is part of a series of proposals designed to improve the QGIS development workflow and document existing policies._

_**!!!!!PLEASE NOTE THAT THIS QEP TARGETS PULL REQUESTS OPENED BY DEVELOPERS WHO HAVE CORE COMMIT RIGHTS ONLY. PULL 
REQUESTS WILL STILL REQUIRE AN EXPLICIT APPROVAL IF THEY ARE OPENED BY A DEVELOPER WHO HAS NOT BEEN GRANTED COMMIT RIGHTS!!!!!!**_

## Proposed Solution

Currently, for an **developer with commit rights to the QGIS repo** to get a pull request merged, they must:

1. Ensure that the PR passes all reasonable CI checks (some exceptions exist to this rule, eg when a check is broken for unrelated reasons (such as broken third party services, or a lint/code analysis/spell check test failing from other parts of a modified file).
2. The PR must be approved by a different developer with core commit rights

(There's an additional, informal but general followed practice that the developer will address all opened concerns / suggestions / etc, even if approval has been given by someone else)

This proposal would revise the second guideline, so that it becomes:

2. The PR can be merged immediately if it has been approved by a different developer with core commit rights.
3. If **NO** comments are raised within a two week period following the PR being submitted, the original developer is free to self-approve and merge the PR. This implicit acceptance ONLY applies to PRs submitted by those with core commit rights, and ONLY to PRs with no comments raised. It is sufficient for another developer to comment "i require more time to review this", "I have thoughts but am on break and cannot provide feedback for another month", etc to **invalidate** the implicit acceptance for a pull request. Comments with no relation to code review, eg "this looks great!", "finally!", etc have no impact on the implicit acceptance.

Please note that the implicit acceptance is only valid for pull requests targeted to non-LTR branches. Changes being submitted to the LTR branches will still require explicit approval prior to merge.

### Example(s)

https://github.com/qgis/QGIS/pull/58337 would be considered implicitly approved -- it was opened by a core developer (@wonder-sk ), has been opened for over two weeks, and the only comments are non-review related ones.

https://github.com/qgis/QGIS/pull/58528 is not considered implicitly approved -- review comments are present, even though they are over two weeks old

https://github.com/qgis/QGIS/pull/58699 is not considered implicitly approved -- while there have been no review comments within two weeks of the PR creation, it was not submitted by a developer with core commit rights

**Comment by rouault** [comment]
+1, with just the following remark:

> 2\. The PR can be merged immediately if it has been approved by a different developer with core commit rights.

Can we amend this to recommend granting at least one day of review in the general case, except:
- if it is something that is related to an emergency, like un-breaking the build of a broken master
- or the PR fixes trivial things, like one liners fixing typos, where another pair of eyes is indeed more than enough.
Otherwise, another core dev might have interesting remarks on the pull request, and depending on their time zone not have the chance to even notice it if has been merged in between.

**Comment by nyalldawson** [comment]
@rouault 

I'm personally ok with both those changes, but I'm nervous about making this particular proposal include multiple independent tweaks to the policies. I think we risk the discussion becoming bogged down with everyone's individual wishlists and we won't get any actual final decisions made as a result.

Given that your changes are applicable (and would be beneficial) regardless of whether this proposal is accepted, could we submit them as a different QEP?

**Comment by rouault** [comment]
> Given that your changes are applicable (and would be beneficial) regardless of whether this proposal is accepted, could we submit them as a different QEP?

yes, that make sense.

So +1 as it is stated

**Comment by Guts** [comment]
Thank you @nyalldawson for bringing up this kind of "meta" topic, it's truly valuable.

I want to clarify from the start that I am not a core developer of QGIS, let alone a core committer. I'm sharing my opinion here as a developer and advocate of the QGIS ecosystem and, more broadly, FOSS4G.

I agree with the observation. I often have to follow up on PRs related to end-user needs/issues to prevent them from being forgotten. It's a real cat-and-mouse game with the "stale bot." I can imagine how frustrating it must be for developers submitting their own changes.

However, the proposed solution to the problem of workload and PR processing time doesn't fully convince me and deserves discussion.

I see that this could introduce some biases:

- It tends to prioritize PRs from core committers since they are directly involved. This creates a kind of privilege tied to their access rights.
- There are times when two weeks is quite short, considering people's availability (vacations, work schedules, etc.). Maybe two weeks is too brief. Without wanting to bargain, why not extend it to three weeks? This would still be slightly shorter than a QGIS release cycle (from an end-user perspective).
- To introduce a counterbalance, perhaps there could be a mechanism where, if PRs are easier to merge, they should also be easier to revert?
- Similarly, should we limit the number of PRs eligible for automerge by a single core committer in the same QGIS version? Or based on the number of files modified?

In any case, the key point is that this should help reduce favoritism among developers from the same company, and stop commits into master or automerges happening without discussion within less than three days (sometimes within the same 24-hour window... in a single time zone! _sic_). So, it's definitely a step in the right direction. Next steps: standardizing commits (commitzen)? introducing “beta” flags in features that are too fresh and therefore disabled by default in LTRs (even in PyQGIS)?

**Comment by nyalldawson** [comment]
@guts

Thanks for the feedback! Here's my thoughts....

> It tends to prioritize PRs from core committers since they are directly involved. This creates a kind of privilege tied to their access rights.

This is 100% the case, and I don't see this as a bad thing. They've been granted this privilege because the project trusts them, and they've demonstrated an in depth knowledge of qgis development and have a proven track record.

>  There are times when two weeks is quite short, considering people's availability (vacations, work schedules, etc.). Maybe two weeks is too brief. Without wanting to bargain, why not extend it to three weeks? 

Mmm... Three weeks is quite a long time. It'll get the stale label before this condition is triggered 🤣. Realistically, Is it really unlikely that a developer would go two weeks without checking through the list and making just a "wait!" comment on an interesting pr?

> To introduce a counterbalance, perhaps there could be a mechanism where, if PRs are easier to merge, they should also be easier to revert?

What would this practically look like? 

> Similarly, should we limit the number of PRs eligible for automerge by a single core committer in the same QGIS version? Or based on the number of files modified?

Is there a good reason for that? I'm trying to cut down the amount of red tape here, not add extra overhead.

**Comment by troopa81** [comment]
I'm -1 on this.

I'm completely aware of the review issue, and I have tried my best recently to increase my review effort, though it's probably still not enough.

It looks like to me that we, as a community, failed to solve a problem, so we make it legit. Still, I understand this is a big and long standing issue, but I would have liked that we try harder, and maybe take a look on how other project manages to deal with it (Is there any other known OS project that choose a way alike as the one proposed here?)

Review is important and has proved to increase code quality, so I think it should not be avoided in any case.

I have the feeling that we favor quantity over quality, and it endangers QGIS durability (there is already code parts difficult to maintain).

I don't have great counter proposal. I think each core committers should review as much as it ask for review. We have started to estimate Pull Request effort in order to split review budget accordingly, maybe we could use that metric to ascertain a balance?

**Comment by rouault** [comment]
> and maybe take a look on how other project manages to deal with it (Is there any other known OS project that choose a way alike as the one proposed here?)

Not the testimony you probably expect, but my sympathy for this QEP mostly comes from the fact that GDAL is struggling even more than QGIS to get reviews, obviously due to its strongly imbalanced contributor code base. So GDAL doesn't even have a rule that a pull request must be approved for someone with merge rights to be able to merge it.
And this is definitely far from being ideal.
Even with a well balanced contributor code base, most people will tend to specialize in parts of the code base and will not feel competent to review contributions in parts they are not. At least, that's my own feeling when looking at QGIS PR queue, and I must fight hard against my imposter syndrome to sometimes give reviews on PRs of topics I don't master (if my stats aren't wrong, I'm familiar with something like 3 to 5% of QGIS code base). And I have a huge bias in doing that for PRs coming from core contributors (because the consequence of me missing something is less likely to have bad impacts than missing something in a contribution from an occasional contributor)

If you look at huge projects like the Linux kernel, they have this concept of subsystem maintainers who are the ones effectively responsible for approving contributions in the area they are responsible for, and doing the in-depth reviews. But those maintainers are a very scarce resource, and I don't know how the economics of that work. And Linux maintainer burnout is a [recurring topic of discussion](https://lwn.net/Articles/952034/)

**Comment by elpaso** [comment]
> If we look at the recent merged Pull Requests, some of them do not contain unit tests. Even, some PRs from core committers. It rarely happens, but it does happen. Is it a serious issue? Does it matter? I honestly don't know. However, this shows that we, as a community, are failing to fully respect our own code quality rules. And I'm afraid that this policy change will make the situation worse.

AFAIK there is no such a rule: tests are strictly required for core changes only. 

I'm not saying that tests in `gui` or `app` aren't useful/welcome but sometimes they do more harm than good (look at the growing list of disabled tests in CI) or just won't worth the effort.

Also, when I'm in volunteer mode and I have a _trivial_ fix for a bug I sometimes ask myself: is it better for QGIS users to make a PR for it without a test or is it better to leave the bug because I don't have the time to write a test?

**Comment by troopa81** [comment]
> Not the testimony you probably expect, but my sympathy for this QEP mostly comes from the fact that GDAL is struggling even more than QGIS to get reviews, obviously due to its strongly imbalanced contributor code base. So GDAL doesn't even have a rule that a pull request must be approved for someone with merge rights to be able to merge it.
And this is definitely far from being ideal.

I think that if we go the way proposed here, we would land on a situation that could be pretty close of the one in GDAL no? I'm not sure it enforces new contributor to come and play (and review).

> Even with a well balanced contributor code base, most people will tend to specialize in parts of the code base and will not feel competent to review contributions in parts they are not. At least, that's my own feeling when looking at QGIS PR queue, and I must fight hard against my imposter syndrome to sometimes give reviews on PRs of topics I don't master (if my stats aren't wrong, I'm familiar with something like 3 to 5% of QGIS code base). And I have a huge bias in doing that for PRs coming from core contributors (because the consequence of me missing something is less likely to have bad impacts than missing something in a contribution from an occasional contributor)

You're right, I have been there too. But I would rather try to improve the situation than accept there is nothing we can do about it. We should accept stupid questions from people that try to review out of their comfort zone. Why not also trying to improve our design documentation to lower the review and contribution barrier entry. If there are stupid questions, that's maybe the design/code is not clear enough.

**Comment by ptitjano** [comment]
> > If we look at the recent merged Pull Requests, some of them do not contain unit tests. Even, some PRs from core committers. It rarely happens, but it does happen. Is it a serious issue? Does it matter? I honestly don't know. However, this shows that we, as a community, are failing to fully respect our own code quality rules. And I'm afraid that this policy change will make the situation worse.
> 
> AFAIK there is no such a rule: tests are strictly required for core changes only.
> 
> I'm not saying that tests in `gui` or `app` aren't useful/welcome but sometimes they do more harm than good (look at the growing list of disabled tests in CI) or just won't worth the effort.

From the current developer guide: "As of November 2007 we require all new features going into master to be accompanied with a unit test. Initially we have limited this requirement to QGIS_core, and we will extend this requirement to other parts of the code base once people are familiar with the procedures for unit testing explained in the sections that follow."

My understanding is that 17 years later "people are familiar with the procedures for unit testing" and therefore this policy should apply to all the core changes.   
I don't want to quibble or derail the discussion. My point is that we don't fully embrace the current code quality policy and I'm afraid that this new policy will make the situation worse.

> Also, when I'm in volunteer mode and I have a _trivial_ fix for a bug I sometimes ask myself: is it better for QGIS users to make a PR for it without a test or is it better to leave the bug because I don't have the time to write a test?

Sorry for the misunderstanding. I was only referring to the new features PRs as written in the developer guide/

**Comment by nyalldawson** [comment]
@rouault 


> > Given that your changes are applicable (and would be beneficial) regardless of whether this proposal is accepted, could we submit them as a different QEP?
> 
> yes, that make sense.

Submitted as https://github.com/qgis/QGIS-Enhancement-Proposals/issues/304

**Comment by nyalldawson** [comment]
This QEP is being archived in order to empty the issue tracker on this repository. Previous discussion and voting on the QEP remains valid and unchanged.
