### ISSUE TITLE
QEP 33: MetaSearch Publishing Enhancements

### ISSUE THREAD

**Issue by NathanW2** [qgis/QGIS-Enhancement-Proposals#33]
# 
# QGIS Enhancement 33: MetaSearch Publishing Enhancements

**Date** 2015/03/26
**Author** Tom Kralidis
**Contact** tomkralidis at gmail dot com
**Last Edited** 2015/03/26
**Status**  Draft
**Version** QGIS 2.10
## Summary

This QEP aims to enhance MetaSearch to provide metadata publishing to CSW providing the following benefits:
- easy, standards-based metadata publishing mechanism of QGIS layer metadata at the core (no duplications or QGIS plugins)
- interchangeable CSW service to publish to (user configured)
- enhanced discovery (better metadata is more easily discovered)
## Overview

QIGS by default provides a Layer Properties Metadata tab which allows a user to enter various values (and select from various select boxes) under various sections like `Description`, `Attribution`, `MetadataUrl`, `LegendUrl`.  The `Properties` section is has both editable (title, etc.) and read only attributes (autogenerated from the data such as bbox, etc.).  These values are stored in the QGIS project file within the `<maplayer>` element.

MetaSearch is a QGIS plugin to interact with metadata catalogue services, supporting the OGC Catalogue Service for the Web (CSW) standard.  MetaSearch provides an easy and intuitive approach and user-friendly interface to searching metadata catalogues within QGIS.

It is proposed to improve MetaSearch to add layer metadata publishing to the plugin seamlessly, efficiently, and in an authoritative manner.

This QEP will support an overall workflow per below:

`manage Layer Metadata (QGIS core) -> publish/update/delete Layer Metadata (MetaSearch) to CSW`
## Proposed [Technical] Solution | Change

MetaSearch will add a 'Publishing' tab, which allows the user to:
- select from the list of CSW endpoints to publish to
- select a metadata format to publish (Dublin Core, ISO)
- click 'Publish', which does a CSW-T Insert or Update to the server.  An 'Update' button will overwrite the entire metadata record on the server.  A 'Delete' button will allow for deleting records from the CSW-T
## Implementation Details
- modify settings tab to allow for authentication against CSW-T
- add publishing tab with 'Publish' 'Update' and 'Delete' buttons
  - metadata values will be derived from Layer Properties Metadata tab values
  - select box to choose format ('Dublin Core', 'ISO').  Metadata XML will be automagically generated against an XML template, filling in values from the Layer Properties Metadata tab

Affected Files
...............
- https://github.com/qgis/QGIS/blob/master/python/plugins/MetaSearch/ui/maindialog.ui
- https://github.com/qgis/QGIS/blob/master/python/plugins/MetaSearch/dialogs/maindialog.py
## Test Coverage

(required for technical solutions/changes if applicable)
## Performance Implications

No performance implications are expected at this time given the lightweight nature of this enhancement to MetaSearch.
## Further Considerations/Improvements

This enhancement can be extended by adding the ability for users to upload user-defined XML templates, or select from more metadata standards/profiles.
## Backwards Compatibility

Given this enhancement there will be no impact on backwards compatibility. There will be a UI design/change which will not break functionality.
## Documentation

Documentation will be enhanced accordingly in https://github.com/qgis/QGIS-Documentation/blob/master/source/docs/user_manual/plugins/plugins_metasearch.rst
## Issue Tracking ID(s)

(required)
## References

(optional)
## Miscellaneous

(optional)
## Voting History

(required)

**Comment by haubourg** [comment]
[edit] transfering comment from old QEP as PR to QEP as issue.. 

Hi , I discover your QEP just now.
At my job, we currently begin to harvest qgs and qlr files to generate metadata ISO 19139, DC and ISO 19110 xmls, and push them to a Geonetwork catalog, using CSW-T too. We use Talend metadata crawler job to do that, which allows data monitoring to keep metadata up to date. 
Working with qgis server in the same time, we got conscious that there is confusion in QGIS between ISO 19xxx norms and WxS metada services.  For instance, Title metadata for layers must be unaccented and well formed to be used in WxS Url's, when a metadata user expects there a quite long and explicit title for metadata record. So the very same field can break WFS requests if user types uncontrolled text in it?
The same goes for project properties.  So, we should start a cleanup work in QGIS to clarify the norms used behind each metadata fields, so that metadata generating use case and OGC WxS services do not collide. I expect to work on that by the end of the year and propo
Opinions on that? 
Cheers
Régis

**Comment by aperi2007** [comment]
Hi,

<quote>
QIGS by default provides a Layer Properties Metadata tab which allows a user to enter various values (and select from various select boxes) under various sections like Description, Attribution, MetadataUrl, LegendUrl. The Properties section is autogenerated from the layer and is ready only. These values are stored in the QGIS project file within the <maplayer> element.
</quote>

AFAIK the Properties section (Abstract Title, Attribution ad so on are not autogenerated and also are not read-only. I wrote them regularly in our qgis project.

Perhaps I miss something ?

Thx.

**Comment by haubourg** [comment]
>AFAIK the Properties section (Abstract, Title, Attribution and so on) are not autogenerated and also are not read-only. I wrote them regularly in our qgis project.
You're right, I use them too. But those are WxS metadata, not ISO 19115. They are here to serve compliant WFS, WMS and WCS. 
What I do is collect those fields to build ISO metadata in Geonetwork. Some concepts match, other don't like Title, and many are missing. ISO 19115 also afford several values for some fields (contact, dates, OnlinRessource...) 
What I look for is a minimalist evolution of those fields in QGIS so that users no longer have to enter anything in Geonetwork UI for more common datasets. Addtionnal metadata come from templates or from data itself. Is that more clear?

**Comment by aperi2007** [comment]
What version of GeoNetwork ?

I Guess if you try to generate a Metadata for Service you have a section for title.

You should find it in 

AFAIK the layer.title should go in the 
dataidentification - citation - title element of ISO19115.

**Comment by aperi2007** [comment]
As a comparation you should use the Editor Inspire of JRC.
http://inspire-geoportal.ec.europa.eu/editor/

Start it and choose for a NEW metadata of Inspire Spatial Data Service 
fill the fileds, (title, and so on) and see what element are filled in XML.

You should see.
The Title is in the 
Data indentification - citation - title.

A.

**Comment by aperi2007** [comment]
However not all the metadata are matching on ISO19115.
You have right.
But is not possible to enhance the return of a getcapabilities to host information that a OGC service don't allow in its xsd.
Otherwise the validation xsd will fail.

**Comment by tomkralidis** [comment]
@aperi2007 thanks for catching this.  I've updated the QEP to differentiate between editable and readonly properties.

**Comment by tomkralidis** [comment]
@aperi2007 @haubourg [QEP 34](https://github.com/qgis/QGIS-Enhancement-Proposals/issues/50) covers metadata editing proper.  This QEP will leverage what's already in the editor.

**Comment by ninsbl** [comment]
NINA (www.nina.no) is very interested in this development (and #50 which is almost a precondition for his one I guess). 

For metadata publishing I would be glad if two to three use-cases could be considered:

For sure there is the 

1. "enterprise" use case: this QEP is adressing (and also NINA would be aiming at), where users have a CSW available they could publish to, however there is also the
2. the “basic single user” use case: individual users without an enterprise SDI in the background will most likely depend on being able to save metadata to XML files or the like. And then there might be a 
3. intermediate or “small to medium company" use case: if a central database (e.g. PostgreSQL / PostGIS) is available (but no CSW) users might wish o be able to store metadata there (e.g. in XML), similar to style information.

In the GRASS metadata addon [1], use cases 1 and 2 are covered and also the QSphere plugin [2] offers publishing to CSW. But a core implementation of this functionality would be great!
 
However, any solution for metadata storage/publishing raises the question how metadata can be bound / linked to data (which might have different formats (DB, file, raster vector)
Possible solutions might be header files of whatever format used for data storage, or additional metadata tables in case of DB storage (but this requires much more development efforts, and potentially messing up header's content). In case of storing metadata to XML file, the question is: how to keep the metadata file linked to a specific dataset? Using uuids could be a solution, which implies methods for keeping the link. What happens if data is modified (inside or outside QGIS)? What happens if data is moved to different location? This is also discussed in #50.

Finally, a question is how and if metadata storage / publishing could (or should) be aligned with efforts in GRASS [1] and GDAL [3].

[1] https://grasswiki.osgeo.org/wiki/ISO/INSPIRE_Metadata_Support
[2] https://qgis.projets.developpement-durable.gouv.fr/projects/qsphere
[3] https://trac.osgeo.org/gdal/ticket/6154

**Comment by nyalldawson** [comment]
This QEP is being archived in order to empty the issue tracker on this repository. Previous discussion and voting on the QEP remains valid and unchanged.
