### ISSUE TITLE
QEP 75: Add concept of "true north" to composer north arrows

### ISSUE THREAD

**Issue by nyalldawson** [qgis/QGIS-Enhancement-Proposals#75]
# QGIS Enhancement 75: Add concept of "true north" to composer north arrows

**Date** 2016/10/10

**Author** Nyall Dawson (@nyalldawson)

**Contact** nyall@north-road.com

**maintainer** Nyall Dawson

**Version** QGIS 3.0, with backports to 2.x series
# Summary

This QEP relates to the decade old feature request/bug https://hub.qgis.org/issues/192

Currently QGIS north arrows only consider grid north, and have no means of handling true (and magnetic) north.

This work is designed to be backported to all maintained branches.
### UX

Currently, North Arrows are created using print composer image items and the only option is to sync the picture rotation with a map item's grid north.

A new combobox will be added below the existing "Sync with map" option, with options "Sync to grid north" and "Sync to true north". The default behaviour will stay at "sync to grid north".
### Calculation

To calculate true north, the follow procedure will be used:
1. Take the center point of the linked map item (P1)
2. Project this point into EPSG:4326 (WGS84) (P1`)
3. Add a small offset to the projected point's latitude, ie move the point a small amount up it's current meridian (P2`)
4. Project this shifted point back to the map's CRS (P2)

The bearing between P1 and P2 will be used as direction to True North.
## Backwards Compatibility

It is intended to backport these changes to 2.14, 2.18 and master_2. This will introduce new strings which will need to be translated.
## Possible follow-ups

The work could be extended by adding an "angle offset" option which is enabled when "sync with map" is checked. This offset could be used to sync an arrow with magnetic north, by first calculating the grid convergence for a desired location/time.
## Issue Tracking ID(s)

https://hub.qgis.org/issues/192
## Votes

(required)

**Comment by nyalldawson** [comment]
@NathanW2 can you mark this as accepted/implemented?

**Comment by sbrunner** [comment]
Looks good but I don't like those words  "true north", shouldn't we speak about?:
* Projection North
* Geodetic North
* Magnetic North

**Comment by nyalldawson** [comment]
@sbrunner FYI this was implemented back in November ;)

**Comment by sbrunner** [comment]
:-) and I'm wrong, https://en.wikipedia.org/wiki/True_north

**Comment by RobDeBagel** [comment]
There was a feature added that rotated images/arrows already, but it would be useful to rotate maps themselves to true/grid north also.

For example, I have a map with a UTM grid that is a part of a topographic map series whose extents are defined using DMS. It is useful to rotate the map so that the extent bounds are as  square with respect to the canvas as is possible.

I can get the convergence for a point on the map using the 'true north' alignment of an image and manually set the rotation for the map, but it's still a hack.

See the image attached. The map should be rotated in this case ~2.8 degrees so that the DMS grid appears roughly square with respect to the canvas.

As this is a map atlas/series, making this parameter data driven is highly useful.

<img width="749" alt="screen shot 2017-03-15 at 13 19 22" src="https://cloud.githubusercontent.com/assets/3732357/23934184/a788696e-0997-11e7-8779-ba4a38dbc386.png">

**Comment by nyalldawson** [comment]
This QEP is being archived in order to empty the issue tracker on this repository. Previous discussion and voting on the QEP remains valid and unchanged.
