### ISSUE TITLE
QEP 83: QGIS Enhancement: Diagram size improvements

### ISSUE THREAD

**Issue by sbrunner** [qgis/QGIS-Enhancement-Proposals#83]
# QGIS Enhancement 83: Diagram size improvements

**Date** 2016/11/23

**Author** Stéphane Brunner (@sbrunner)

**Contact** stephane dot brunner at camptocamp dot com

**maintainer** @user

**Version** QGIS 3.X

### Change the circle size representation into concentric circles

From:
![old](https://cloud.githubusercontent.com/assets/353872/20564802/2109f976-b18f-11e6-97b1-84301d5ac03c.png)

To (the style and title should stay):
![legende](https://cloud.githubusercontent.com/assets/353872/20564821/31c37cba-b18f-11e6-8d94-5a7bf9f9cba6.png)

### Know what represents the value

* Add a attribute legend in the Diagram/Size panel under the Attribute.
![legend-config](https://cloud.githubusercontent.com/assets/353872/20564846/5343336c-b18f-11e6-8b6e-c8d53bd2957e.png)
* Add the legend text in the legend on the top of the imbricate circles.

### Be able to choose which value we want to see:

* Add a list (named: "Size classes") in the Diagram/Legend panel (add-remove-move buttons are missing).
![class-config](https://cloud.githubusercontent.com/assets/353872/20564849/59a4cac2-b18f-11e6-9bf8-3ad908e3cfcb.png)
* Use it :-)

### Proposed Solution

Described above

### Affected Files

Not yet known

## Performance Implications

Shouldn't change

## Further Considerations/Improvements

*(optional)*

## Backwards Compatibility

This new representation will be optional.

## Issue Tracking ID(s)

*(optional)*

## Votes

(required)

**Comment by haubourg** [comment]
Nice idea, I wanted that when I financed variable size assistant but it seemed unfeasable in qt4. 
Could it be possible to have the same legend feature for size varying symbols (not diagram) in classical symbology? This involves map legend (where symbols are truncated for bigger sizes) and composer legend.

**Comment by DelazJ** [comment]
Nice indeed. Only yesterday I reported several feature requests/bugs related to diagram and size assistant symbology (from http://hub.qgis.org/issues/15877 to http://hub.qgis.org/issues/15882). Main things I think that could be relevant for this QEP are:
* being able to set the number of circles
* being able to set the value to show in the legend (and the size of the circles change accordingly) e.g, in your example one may like to show size for 1700, 5100 and 15400; I don't know if it's meant in the above
  > Be able to choose which value we want to see

* maybe with an option to display min and/or max values of the "field" in the legend

**Comment by sbrunner** [comment]
@DelazJ 
The idea with the diagram size class is to define all the size we want to display (e.g.  2000, 5000, 10000), then the two first points will be covered.

**Comment by nyalldawson** [comment]
@sbrunner can you share some details  how you'll implement this in the code? 

I scoped this out for a customer a year or so ago (unfortunately funding was not secured), but I'm keen to see the implementation details and may be able to share some ideas from my old proposal.

**Comment by timlinux** [comment]
@sbrunner thanks for this initiative - it will be a most welcome improvement!

**Comment by sbrunner** [comment]
> can you share some details how you'll implement this in the code?

I just see that's looks feasible, I don't have an exact plan in my head, I purpose do and purpose a prototype.

**Comment by sbrunner** [comment]
The current prototype:
https://github.com/qgis/QGIS/compare/master...sbrunner:diagram-size-legend

The current result:
![5c](https://cloud.githubusercontent.com/assets/353872/20918011/2fa47c6c-bb95-11e6-8863-53d864e078e8.png)

**Comment by nyalldawson** [comment]
@sbrunner

I dug out some notes/test code from my old work here. Here's some notes:

"Nested legends will be enabled by setting a “Nested” option for a legend group, via the right-click context menu on a legend group heading. This would allow the use of mixed legends consisting of both nested and non-nested groups.

A nested legend group will be rendered by drawing the legend symbols over the top of each other. The legend symbols will be drawn using their original symbol style, so it is up to the user to ensure that appropriate symbols are used to maintain visibility when the symbols are drawn overlapping (eg, totally opaque symbols would not be appropriate for use in a nested legend as underlying symbols will not be
visible beneath the overlapping symbols).

To allow users to control the appearance of nested symbol legends, it will be possible to set the “vertical
alignment” used when rendering the overlapping symbols. This will allow top, middle and bottom alignment, as shown below:

![screenshot from 2016-12-13 13-57-11](https://cloud.githubusercontent.com/assets/1829991/21127093/214a8e16-c13c-11e6-9508-c3634194279b.png)

This setting will be accessible via the right-click menu on a legend group, but only enabled when the group is set to render as a nested group.

Additionally, to allow creation of aesthetic nested legends, a new option for controlling the horizontal alignment of legend symbols will be added (implementing http://hub.qgis.org/issues/12968). Currently, QGIS always renders legend symbols using a left alignment. Horizontal left, center and right alignments will be added so that both nested and non-nested legend symbols can be drawn using these additional alignment options. Horizontal alignment of legend symbols will  be set via a combobox which applies to ALL symbols within the legend item. The default horizontal alignment for legends will be changed to center alignment.

Text labels and leader lines

Finally, creation of nested legends will be facilitated through new options controlling the labelling of legend symbols for nested legends:

![screenshot from 2016-12-13 13-58-14](https://cloud.githubusercontent.com/assets/1829991/21127104/372d2d9c-c13c-11e6-9ca2-35513123178d.png)

When a legend group is set to nested rendering, labels will be drawn to align vertically with the symbols and include a leader line from the horizontal center of the symbol to the corresponding legend text. The vertical placement of legend text and leader lines will follow the vertical alignment setting for the nested legend, eg if the legend is set to top alignment then the labels will be drawn at the bottom of symbols, and if the legend is set to bottom alignment the legend text will be drawn at the top of symbols (see diagram above). The text leader lines will be rendered in the same color as the legend font color. Additionally, a new option will be added for controlling the vertical alignment for nested legend text, eg vertically aligned so that either the label top, center or bottom is aligned with the symbol leader line.

Possible Additional Improvements which Could be Included

The following additional improvements are not in scope of this current proposal, but if desirable the proposal could be amended to included these additional features:

• As noted above, the proposed changes include only rendering the original legend symbol in a nested
 fashion without modification. While this may be suitable for some symbol types, it would not be appropriate for opaque, filled symbols, where the overlapping symbols would obscure parts of underlying symbols. A possible related improvement would be allowing users to change the actual rendered symbol within the legend so that it may differ from the symbol used to render features/diagrams within a map. Eg, the map would use the opaque, filled circle symbol for rendering and the legend symbol could be tweaked to draw a non-filled outline of the circle symbol."

I've got some messy proof of concept code at https://github.com/nyalldawson/QGIS/tree/legend_nested. Not sure how useful this is at all.

I'm personally a -1 on any implementation which is diagram specific. I think this needs to be implemented in a way that allows it to be used with all legend items, including things like graduated size marker layers. That's a common request and the feature should be implemented in a way that allows it to be reused for these purposes too.

**Comment by haubourg** [comment]
> I'm personally a -1 on any implementation which is diagram specific. I think this needs to be implemented in a way that allows it to be used with all legend items, including things like graduated size marker layers. That's a common request and the feature should be implemented in a way that allows it to be reused for these purposes too.

Agreed with that. A generic implementation is really necessary. Remember that diagram are a edge use case in cartography, when size varying symbols are much more readable and powerful, but poorly used probably because of a good legend item .

**Comment by sbrunner** [comment]
> (eg, totally opaque symbols would not be appropriate for use in a nested legend as underlying symbols will not be
visible beneath the overlapping symbols).

For me it should work if we render the symbols in the right order ...

+1 for an implementation that's not diagram specific :-)

**Comment by sbrunner** [comment]
Fixed with serials commits...
