### ISSUE TITLE
Translation of .qgs project files

### ISSUE THREAD

**Issue by m-kuhn** [qgis/QGIS-Enhancement-Proposals#90]
# QGIS Enhancement: Translation of .qgs project files

**Date** 2017/02/23

**Author** Matthias Kuhn (@m-kuhn)

**Contact** matthias@opengis.ch

**maintainer** @m-kuhn

**Version** QGIS 3.0

# Summary

QGIS is used in different environments also with different localization requirements. Plugins can be translated using Qt possibilities (`tr('Hi')` + pylupdate + lrelease), the QGIS interface itself is also translated.

Plugins often ship with preconfigured project files. It would be great to be able to ship these with translation information. This QEP proposes to do this in a very similar way that the Qt ecosystem does this always.

## Workflow

1. Create a .qgs project file in a base language (e.g. English) [QGIS, project maintainer]
2. Create a .ts translation file for language(s) [QGIS, project maintainer]
3. Translate the .ts file [linguist / transifex ..., translation team]
4. Compile the .ts file to a .qm file [lrelease, project maintainer]
5. When loading a .qgs project, locate .qm files (e.g. `i18n/my_project_de.qm`, possibly configurable) containing translation [QGIS, user (automatically)]
6. Enjoy a localized project [QGIS, user (very happy)]

## Translatable objects

This is a non conclusive list of objects to translate 

 * attribute alias
 * layer names
 * layer group names
 * project name
 * forms (tab titles, group box titles)
 * labels
 * expressions
 * action titles
 * constraint messages
 * composer texts (?)
 * ValueRelation -> value column
 * ValueMap -> values
 * ...

## Proposed Solution

QGIS will be enhanced with additional functionalities to generate translation sources and to translate strings at runtime.

### Translation file generator (.ts)

In the project properties window, there will be a new button "Generate translation file". This scans the currently loaded project for translatable strings (see above and special notes for expressions below).

This will be a growing list of strings as new features are added and missing bits are discovered.

There will not only be a button to generate the translation file, but even a method :tada: 

```cpp
QgsProject::generateTsFile( const QString& filePath );
```

A signal will be introduced that allows for code outside of the core library to report translation targets.

```cpp
QgsApplication::translateObjects( QgsTranslationContext* translationContext );
```
While your code can do something along the lines of

```py
QgsApplication.instance().connect(self.reportTranslatableObjects)

def reportTranslatableObjects(self, translationContext):
    # project = translationContext.project() # In case you need the qgis project that requested the translation

    # Register a user configurable string for your plugin for translation
    translationContext.registerTranslation('my_awesome_plugin:name', self.name)
```
### Translator

The `QgsProject` class will have a new property `translator` that contains a `QTranslator` which is initialized early on when the project is loaded and shall be used by the API to translate content.

### Expressions

A new expression function `tr( string )` will be added, that translates content. Expressions will need to be "whitelisted" to have them scanned during .ts file generation phase (first thing is probably labels).

### Saving a translated project

When translating a field name, the (technical) attribute name will be written to the .ts file while the attribute alias will be overwritten by the translator. For the project name or other translatable strings there is just a single variable that is maintained and that will be overwritten by the translator. Therefore, when saving a file that was loaded with a translator, the original values will be lost.

To avoid accidentally overwriting the source project, the file name will therefore automatically be suffixed with the locale abbreviation. E.g. opening `my_project.qgs` with `fr` translation will result in `my_project_fr.qgs` being used by default when saving it.

In the future this can be changed to a more dynamic concept.

## Alternatives

An alternative approach would be a separate application could take care of this by taking an (untranslated) project file and generating a translated project file version.

## Backwards Compatibility

It's a new feature. It won't break anything but will not automatically be available on old releases.

## Votes

(required)

**Comment by 3nids** [comment]
Great initiative!

I think one of the key here is to be able to save the same project but localized (avoiding saving a translated project). I am just wondering if what you describe as "a more dynamic concept" should not be added from scratch as it would make things more complicated to add it later (I suppose).

I'm just wondering if we shouldn't use an in app solution to translate the strings directly (while it would still be possible to generate ts files for translating a big project at once). I think it would ease a lot the translation process.

Thinking at loud, I'm just wondering if the source information is the data or rather its description. In other words, in case of field translation, are you translating the field source name or its alias? 
Though fields are a specific case, could we see translation as bringing aliases to every object?

So, you would have aliases but no main language. For each object you have an ID and one alias per language.
IDs would be determined automatically whenever possible (layer, fields, relation, constraint, etc) or defined by the first entered alias (form group or tab, labels, etc).

Editing strings in QGIS only modififes the language (alias) your are currently working with.

Not sure I have the whole picture in mind though.
This idea might be too complex/long to code.

Your approach seems more lightweight and flexible. I'm just afraid of usability due to

* translating outside of QGIS
* not being able to save on the same project (to me, it's almost a requirement).

Sorry for thinking out loud ;)

**Comment by m-kuhn** [comment]
Thanks for the feedback. It's much appreciated.

I think for fields the source string will be the field name, but the alias will be set. Therefore it's a bit special since we are not losing the source string.

The lightweight approach I described here should work for strings aliased or not and avoid *accidentally* overwriting the project. I have some ideas how to overcome these limitations (see below) but I think that they can very well be added at a later point without requiring big changes to this work.

In short: I think this project can help us to get started with translation and we can improve on it later on.

Having translation inside QGIS would be nice but will be a lot of (not only) UI work. I think we can easily add a UI for this and a possibility to save this inside the QGIS project (or a zipped QGIS project) later on.

In short: I think this project can help us to get started with translation and we can improve on it later on.

Ideas to overcome the separate project limitation
--------------

**These ideas are just listed here for an outlook and are not part of this proposal**. If you have doubts that these can be treated as simple extensions and require changes to this QEP, please say so. Or of course if you already want to fund its development now :yum: 

Introducing aliases everywhere would be an approach, but I am afraid that it will make the API more complex to handle and require some fancy user interface changes to have both available, the source string for the "project maintainer" and the translated string for the "everyday user".

```cpp
QString name() const;
void setRawName( const QString &name );
QString rawName() const;
```

Another approach would be to have a "developer mode" in which strings would be untranslated (so raw source strings present everywhere). And either not allow making changes to translated strings when not in developer mode (group names etc. will be read only) or set a different project name by default if someone overwrites one of the translated fields. This will require minimal UI and API changes and could offer a very good workflow.

**Comment by 3nids** [comment]
I'm just thinking that we are not really in a standard translation process. In many places we're giving a human readable phrase to an object (a relation, a layer, a field, etc), we're not really translating. 

I don't think it requires changes in the API, "just" in the code. 

There would a concept of active language and fallback language (which could be determined automatically depending on availability in current project). These concepts would be attached to the project.

So if I open my project in French with English as fallback, for each translatable objects being named in QGIS, I'll have

* read = coalesce( French, English, all_other_available_language_in_random_order )
* write = set_french


If we take the example of the value column of the value relation widget, in the XML I'll have something like 

```
<value_en>my_english_column</value_en>
<value_fr>my_french_column</value_fr>
<value_de></value_de>
```

It will use my_french_column. Now, if opening in German, it will use the English (master) one.

I think it makes more sense this way, because If I open the English project and change the column, why should the other one change too? And I think it is the case for all listed types of translatable objects. There is not really a proper "master" language as is usually used in translation processes we are used too.


Now I agree this might be a bit more work, but do you think that much?

**Comment by m-kuhn** [comment]
> There would a concept of active language and fallback language (which could be determined automatically depending on availability in current project). These concepts would be attached to the project.

I think it's best to stick to the standard solution where we have one QGIS project file in a *master language* and a separate translation loaded (from .ts/.qm or .qgs). That's how all the others do and how we can integrate transifex and have the smallest change in the project file.

**Comment by 3nids** [comment]
I think you've convinced me. Your approach is clearer, more standard and won't break project file.

**Comment by haubourg** [comment]
Hi all,  
We are thinking of extending QGIS server with this internationalization capabilities since OGC services allow that. Anyone has been working on this before ? 
Do you think that this QEP can be tagged as done or closed?

**Comment by signedav** [comment]
Hi @haubourg 
The functionality to translate a local .qgs project is fully implemented.

It's not integrated for every object that could be translated, but the basics are there to extend it easily. 
The Pull Requests are linked above - another improvement has been this https://github.com/qgis/QGIS/pull/7694

A description of how it works (written for end users) you can find here http://old.opengis.ch/2018/09/11/qgis-speaks-a-lot-of-languages/

@m-kuhn do you think this QEP should be closed? I'm not sure how it's handled. Main part is integrated but not every possible extension.

**Comment by m-kuhn** [comment]
Integrating this into QGIS server sounds like a very nice idea, even better if it can be done in an OGC compliant way.

**Comment by mdouchin** [comment]
cc @rldhont

**Comment by RobiFag** [comment]
Hi all,
in the last few days, we have worked on a python script in order to update the .ts file for the project content translation. We noticed that if a .ts file has already been created and translated when the project content change (for instance a new layer is added), the new generated .ts file does not include the already translated strings. 
The script assumes that there is a .ts file for each language in the project folder (named project_name _ *. ts), compares the .ts file created from the project properties with those found in the folder and adds the missing parts to them keeping the already made translations.

We would like to share it because, despite being a rough script, we think it can be useful and maybe a good starting point. We would also like to integrate it but unfortunately, we do not know how or where to integrate it into the QGIS code.
If anyone deems it useful, feel free to improve the script and/or integrate it into the code.

Any help or suggestions are welcome!

Could something similar also be done for Qgis server and/or lizmap web client? https://github.com/3liz/lizmap-web-client/issues/453

[update_project_ts_file.zip](https://github.com/qgis/QGIS-Enhancement-Proposals/files/4077440/update_project_ts_file.zip)

**Comment by m-kuhn** [comment]
Thank you for sharing this!

> We would also like to integrate it but unfortunately, we do not know how or where to integrate it into the QGIS code.

You could also transform this script into a plugin as a first step

**Comment by RobiFag** [comment]
> Thank you for sharing this!
> 
> > We would also like to integrate it but unfortunately, we do not know how or where to integrate it into the QGIS code.
> 
> You could also transform this script into a plugin as a first step

Yes sure, I'll work on it as soon as possible!
